# Generated by Django 4.2.1 on 2023-05-30 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_name', models.CharField(max_length=200)),
                ('e_desc', models.CharField(max_length=500, null=True)),
                ('Poster', models.ImageField(null=True, upload_to='events')),
                ('Location', models.TextField()),
                ('start_date', models.DateField(blank=True, verbose_name='startdate(mm/dd/yyyy)')),
                ('end_date', models.DateField(blank=True, verbose_name='enddate(mm/dd/yyyy)')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userdetails')),
            ],
        ),
    ]
