# Generated by Django 4.2.1 on 2023-05-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profpictures'),
        ),
    ]
